# Generated by Django 4.2.22 on 2025-07-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_demo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
