# Generated by Django 4.2.22 on 2025-07-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidates_education_candidates_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='experience',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
