# Generated by Django 4.2.22 on 2025-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_candidates_experience_alter_candidates_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
